### ISSUE TITLE
Feature Admin for sp2016 not returning Upgrade or Cleanup items

### ISSUE THREAD

**Issue by swanlake-it** [achimismaili/featureadmin#7]
Hi, I'm not sure if I'm having trouble with the tool or if it's a user issue (probably the latter ;))

I'm using

SharePoint Feature Admin
Current version 3.0.4.0

Created by Achim Ismaili in 2021
https://www.featureadmin.com

against my SP2016 farm. I ran test-spcontentdatabase against one of my farm's, and it returned multiple MissingFeatures, MissingSetupFiles, MissingWebParts, and MissingAssemblys.

Activation picks up my farm's sites, and displays items in the log.

Upgrade displays "No activated features were found during farm load that require an upgrade. All activated features in the farm seem to be up to date. Please make sure, farm load is already completed (see progress bar in the footer)."

Cleanup: "Currently, no faulty/orphaned activated features that require a clean up were found during farm load.
So, currently, all activated features in the farm seem to be clean, meaning, they seem to have a valid definition.Nevertheless, if orphaned feature definitions exist by checking the scope-filter 'undefined' on the left window. This filter is always set when swithing to the cleanup view. If after a reload no faulty activated features were found, but 'undefined' feature definitions show up on the left, it is usually recommended to uninstall them."

I'm a little confused. It seems that the tool isn't picking up any of the Missing items turned up by test-spcontentdatabase or the FeatureAdmin log list.

Thank you for any guidance, much appreciated.

**Comment by achimismaili** [comment]
Hi swanlake-it, 
from the current information provided, I don't exactly know, what the issue is, but I agree, that something does not seem to be all right here. 
I suggest we dig a little deeper in that problem.

As you probably know, on the left side in the feature admin, you usually find your feature definitions found in the farm, on the right side, there are the activated instances. 

**feature info**
Could we pick e.g. one example feature from your test-spcontentdatabase, that is supposed to be missing?
What information do you have about this feature-id?
Name, ID, Scope, Compatibility level?
Is it a MS feature or a custom one? Do you know, if it came from a farm solution, a sandboxed solution?

**featureadmin handling questions**
If you have the feature-id, then did you try to search for this featureid in featureadmin (on the left and on the right)? If yes, did it find something and if yes, what?
Do you have the checkbox "elevated privileges" enabled, and did you run featureadmin as local admin AND as farm admin with elevated privileges?
On which server are you running it? does it have the webfrontend role? 
(Just to make sure, you are really seeing some of your custom features and you are not seeing s.th. like DEMO mode in the title of the feature admin, right?)

**Comment by swanlake-it** [comment]
Hi, here's some examples from the output:
02/09/2021 13:13:19.40                 powershell (0x208C)       0x284C  SharePoint Foundation Upgrade SPSiteWssSequence2                ajy6o     WARNING           Feature could not be upgraded. Exception: Feature definition id '99c34202-066a-43bc-9c99-10a96e073f39' could not be found.   b8a2a99f-840b-b0e3-ff17-c36a910c45e9

In FeatureAdmin, on FE as FarmAdmin, elevated privileges, I reloaded the farm, put 99c34202-066a-43bc-9c99-10a96e073f39 in Feature Definitions search in left side, Scope Filters are empty, nothing appears. 

Do I need to tweak my search? 

Thanks!

**Comment by achimismaili** [comment]
Hi swanlake-it,

thanks for the details.

Let me ask one important question first:
Is my understanding correct, that the failing content database is not yet added to the farm?
In that case, the featureadmin has no chance to find anything about this content database, as it is only crawling through the farm, and only to content databases connected to the farm. 

If that's the case, you should run the featureadmin in the SharePoint farm, where you got this content db from to find out, what feature that is ...

**Comment by achimismaili** [comment]
Closing, as there is no response.
Most likely, swanlake-it tried to run feature-admin against a non farm attached SharePoint content database, which is not possible.
the feature admin only provides data from within a SharePoint farm.
